trigger:
  branches:
    include:
    - main
    - infra/*
  paths:
    include:
    - infra/*

variables:
  - group: 'SageHealthy_infra_variables'

stages:
  - stage: Lakehouse_Storage_Account
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/storage_accounts/storage_accounts.json'
            overrideParameters: '-project $(PROJECT) -environment $(ENVIRONMENT)  -storageAccountName $(LAKEHOUSE_STORAGE_ACCOUNT) -bronzeLayer $(LAKEHOUSE_BRONZE_LAYER) -silverLayer $(LAKEHOUSE_SILVER_LAYER) -goldLayer $(LAKEHOUSE_GOLD_LAYER)'
            deploymentMode: 'Incremental'
            deploymentName: 'storage_accounts'
         
  - stage: Lakehouse_Databricks
    jobs: 
      - job: DeployDatabricksWorkspace
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/databricks/databricks.json'
            overrideParameters: '-project $(PROJECT) -environment $(ENVIRONMENT) -databricksWorkspaceName $(DATABRICKS_WORKSPACE_NAME)'
            deploymentMode: 'Incremental'
            deploymentName: 'databricks'
          
  - stage: Lakehouse_DataFactory
    jobs: 
      - job: DeployDataFactory
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/data_factory/data_factory.json'
            overrideParameters: '-project $(PROJECT) -environment $(ENVIRONMENT) -factoryName $(DATAFACTORY_NAME)'
            deploymentMode: 'Incremental'
            deploymentName: 'dataFactoryDeployment'           
            
  - stage: Lakehouse_Synapse
    jobs: 
      - job: DeploySynapse
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(SERVICE_CONNECTION)'
            subscriptionId: '$(SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(RESOURCE_GROUP)'
            location: '$(REGION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/synapse/synapse.json'
            overrideParameters: '-vaultName $(KEY_VAULT_NAME)  -synapseWorkspaceName $(SYNAPSE_WORKSPACE_NAME) -synapseStorageAccount $(LAKEHOUSE_STORAGE_ACCOUNT) -synapseStorageAccountFilesystem $(SYNAPSE_CONTAINER) -adminPasswordsecretName $(SQL_PASSWORD_SECRET) -adminLoginUsersecretName $(SQL_USERNAME_SECRET) -vaultResourceGroupName $(KEY_VAULT_RESOURCE_GROUP)'
            deploymentMode: 'Incremental'
            deploymentName: 'synapse'